# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from pydantic import Field

from .base_model import BaseModel


class BuildProfile(BaseModel):
    build_profile: "BuildProfileBuildProfile" = Field(alias="buildProfile")


class BuildProfileBuildProfile(BaseModel):
    job_id: str = Field(alias="jobId")


BuildProfile.update_forward_refs()
BuildProfileBuildProfile.update_forward_refs()
