# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class ChangeLogSource(BaseModel):
    source_history: List["ChangeLogSourceSourceHistory"] = Field(alias="sourceHistory")


class ChangeLogSourceSourceHistory(BaseModel):
    commit_info: "ChangeLogSourceSourceHistoryCommitInfo" = Field(alias="commitInfo")
    project: str
    source_name: str = Field(alias="sourceName")


class ChangeLogSourceSourceHistoryCommitInfo(BaseModel):
    cluster_id: Optional[str] = Field(alias="clusterId")
    operation: Optional[str]
    user_id: Optional[str] = Field(alias="userId")
    timestamp: Any
    version: Any


ChangeLogSource.update_forward_refs()
ChangeLogSourceSourceHistory.update_forward_refs()
ChangeLogSourceSourceHistoryCommitInfo.update_forward_refs()
