# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from pydantic import Field

from .base_model import BaseModel


class CreateProfileSchema(BaseModel):
    create_profile_schema: "CreateProfileSchemaCreateProfileSchema" = Field(
        alias="createProfileSchema"
    )


class CreateProfileSchemaCreateProfileSchema(BaseModel):
    name: str


CreateProfileSchema.update_forward_refs()
CreateProfileSchemaCreateProfileSchema.update_forward_refs()
