# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from pydantic import Field

from .base_model import BaseModel


class CreateDataSource(BaseModel):
    create_data_source: "CreateDataSourceCreateDataSource" = Field(
        alias="createDataSource"
    )


class CreateDataSourceCreateDataSource(BaseModel):
    name: str


CreateDataSource.update_forward_refs()
CreateDataSourceCreateDataSource.update_forward_refs()
