# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List

from pydantic import Field

from .base_model import BaseModel


class CreateCustomAttribute(BaseModel):
    create_custom_attribute: "CreateCustomAttributeCreateCustomAttribute" = Field(
        alias="createCustomAttribute"
    )


class CreateCustomAttributeCreateCustomAttribute(BaseModel):
    name: str
    custom_attributes: List[
        "CreateCustomAttributeCreateCustomAttributeCustomAttributes"
    ] = Field(alias="customAttributes")


class CreateCustomAttributeCreateCustomAttributeCustomAttributes(BaseModel):
    name: str
    expression: str


CreateCustomAttribute.update_forward_refs()
CreateCustomAttributeCreateCustomAttribute.update_forward_refs()
CreateCustomAttributeCreateCustomAttributeCustomAttributes.update_forward_refs()
