# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List

from pydantic import Field

from .base_model import BaseModel


class CreateBucketAttribute(BaseModel):
    create_bucket_attribute: "CreateBucketAttributeCreateBucketAttribute" = Field(
        alias="createBucketAttribute"
    )


class CreateBucketAttributeCreateBucketAttribute(BaseModel):
    name: str
    bucket_attributes: List[
        "CreateBucketAttributeCreateBucketAttributeBucketAttributes"
    ] = Field(alias="bucketAttributes")


class CreateBucketAttributeCreateBucketAttributeBucketAttributes(BaseModel):
    name: str
    buckets: List["CreateBucketAttributeCreateBucketAttributeBucketAttributesBuckets"]


class CreateBucketAttributeCreateBucketAttributeBucketAttributesBuckets(BaseModel):
    filter: str


CreateBucketAttribute.update_forward_refs()
CreateBucketAttributeCreateBucketAttribute.update_forward_refs()
CreateBucketAttributeCreateBucketAttributeBucketAttributes.update_forward_refs()
CreateBucketAttributeCreateBucketAttributeBucketAttributesBuckets.update_forward_refs()
