# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class DataSourceList(BaseModel):
    profile_sources: List["DataSourceListProfileSources"] = Field(
        alias="profileSources"
    )


class DataSourceListProfileSources(BaseModel):
    description: Optional[str]
    name: str
    title: Optional[str]


DataSourceList.update_forward_refs()
DataSourceListProfileSources.update_forward_refs()
