# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SourceKind


class DataSourceSummary(BaseModel):
    data_source_by_name: "DataSourceSummaryDataSourceByName" = Field(
        alias="dataSourceByName"
    )


class DataSourceSummaryDataSourceByName(BaseModel):
    attributes: Optional[List[str]]
    connection: Optional["DataSourceSummaryDataSourceByNameConnection"]
    description: Optional[str]
    kind: SourceKind
    name: str
    primary_key: Optional[str] = Field(alias="primaryKey")
    title: Optional[str]


class DataSourceSummaryDataSourceByNameConnection(BaseModel):
    name: str


DataSourceSummary.update_forward_refs()
DataSourceSummaryDataSourceByName.update_forward_refs()
DataSourceSummaryDataSourceByNameConnection.update_forward_refs()
