# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List

from pydantic import Field

from .base_model import BaseModel


class DeleteCustomAttribute(BaseModel):
    delete_custom_attribute: "DeleteCustomAttributeDeleteCustomAttribute" = Field(
        alias="deleteCustomAttribute"
    )


class DeleteCustomAttributeDeleteCustomAttribute(BaseModel):
    name: str
    custom_attributes: List[
        "DeleteCustomAttributeDeleteCustomAttributeCustomAttributes"
    ] = Field(alias="customAttributes")


class DeleteCustomAttributeDeleteCustomAttributeCustomAttributes(BaseModel):
    name: str
    expression: str


DeleteCustomAttribute.update_forward_refs()
DeleteCustomAttributeDeleteCustomAttribute.update_forward_refs()
DeleteCustomAttributeDeleteCustomAttributeCustomAttributes.update_forward_refs()
