# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List

from pydantic import Field

from .base_model import BaseModel


class DeleteBucketAttribute(BaseModel):
    delete_bucket_attribute: "DeleteBucketAttributeDeleteBucketAttribute" = Field(
        alias="deleteBucketAttribute"
    )


class DeleteBucketAttributeDeleteBucketAttribute(BaseModel):
    name: str
    bucket_attributes: List[
        "DeleteBucketAttributeDeleteBucketAttributeBucketAttributes"
    ] = Field(alias="bucketAttributes")


class DeleteBucketAttributeDeleteBucketAttributeBucketAttributes(BaseModel):
    name: str
    buckets: List["DeleteBucketAttributeDeleteBucketAttributeBucketAttributesBuckets"]


class DeleteBucketAttributeDeleteBucketAttributeBucketAttributesBuckets(BaseModel):
    filter: str


DeleteBucketAttribute.update_forward_refs()
DeleteBucketAttributeDeleteBucketAttribute.update_forward_refs()
DeleteBucketAttributeDeleteBucketAttributeBucketAttributes.update_forward_refs()
DeleteBucketAttributeDeleteBucketAttributeBucketAttributesBuckets.update_forward_refs()
