# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from pydantic import Field

from .base_model import BaseModel


class DeleteDataSource(BaseModel):
    delete_data_source: bool = Field(alias="deleteDataSource")


DeleteDataSource.update_forward_refs()
