# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from pydantic import Field

from .base_model import BaseModel


class DeleteProfileSchema(BaseModel):
    delete_profile_schema: bool = Field(alias="deleteProfileSchema")


DeleteProfileSchema.update_forward_refs()
