# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class FeaturesFromPreview(BaseModel):
    preview_source: "FeaturesFromPreviewPreviewSource" = Field(alias="previewSource")


class FeaturesFromPreviewPreviewSource(BaseModel):
    features: List["FeaturesFromPreviewPreviewSourceFeatures"]


class FeaturesFromPreviewPreviewSourceFeatures(BaseModel):
    feature_name: str = Field(alias="featureName")
    data_type: Optional[str] = Field(alias="dataType")
    source_name: str = Field(alias="sourceName")


FeaturesFromPreview.update_forward_refs()
FeaturesFromPreviewPreviewSource.update_forward_refs()
FeaturesFromPreviewPreviewSourceFeatures.update_forward_refs()
