# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from pydantic import Field

from .base_model import BaseModel


class IngestSource(BaseModel):
    ingest_source: "IngestSourceIngestSource" = Field(alias="ingestSource")


class IngestSourceIngestSource(BaseModel):
    job_id: str = Field(alias="jobId")


IngestSource.update_forward_refs()
IngestSourceIngestSource.update_forward_refs()
