# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import MeasureFrequency


class ProfileSchemaByName(BaseModel):
    profile_schema_by_name: "ProfileSchemaByNameProfileSchemaByName" = Field(
        alias="profileSchemaByName"
    )


class ProfileSchemaByNameProfileSchemaByName(BaseModel):
    primary_source: "ProfileSchemaByNameProfileSchemaByNamePrimarySource" = Field(
        alias="primarySource"
    )
    joins: Optional[List["ProfileSchemaByNameProfileSchemaByNameJoins"]]
    custom_attributes: List[
        "ProfileSchemaByNameProfileSchemaByNameCustomAttributes"
    ] = Field(alias="customAttributes")
    bucket_attributes: List[
        "ProfileSchemaByNameProfileSchemaByNameBucketAttributes"
    ] = Field(alias="bucketAttributes")


class ProfileSchemaByNameProfileSchemaByNamePrimarySource(BaseModel):
    name: str
    attributes: Optional[List[str]]
    name: str
    profile_group: Optional[str] = Field(alias="profileGroup")


class ProfileSchemaByNameProfileSchemaByNameJoins(BaseModel):
    name: str
    attributes: Optional[List[str]]
    profile_group: Optional[str] = Field(alias="profileGroup")


class ProfileSchemaByNameProfileSchemaByNameCustomAttributes(BaseModel):
    name: str
    expression: str
    window: Optional[MeasureFrequency]


class ProfileSchemaByNameProfileSchemaByNameBucketAttributes(BaseModel):
    name: str
    buckets: List["ProfileSchemaByNameProfileSchemaByNameBucketAttributesBuckets"]


class ProfileSchemaByNameProfileSchemaByNameBucketAttributesBuckets(BaseModel):
    name: str
    filter: str


ProfileSchemaByName.update_forward_refs()
ProfileSchemaByNameProfileSchemaByName.update_forward_refs()
ProfileSchemaByNameProfileSchemaByNamePrimarySource.update_forward_refs()
ProfileSchemaByNameProfileSchemaByNameJoins.update_forward_refs()
ProfileSchemaByNameProfileSchemaByNameCustomAttributes.update_forward_refs()
ProfileSchemaByNameProfileSchemaByNameBucketAttributes.update_forward_refs()
ProfileSchemaByNameProfileSchemaByNameBucketAttributesBuckets.update_forward_refs()
