# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import Any, List

from pydantic import Field

from .base_model import BaseModel


class ProfileList(BaseModel):
    profiles: List["ProfileListProfiles"]


class ProfileListProfiles(BaseModel):
    attributes: List["ProfileListProfilesAttributes"]
    profile_i_d: str = Field(alias="profileID")


class ProfileListProfilesAttributes(BaseModel):
    key: str
    source: str
    type: str
    value: Any


ProfileList.update_forward_refs()
ProfileListProfiles.update_forward_refs()
ProfileListProfilesAttributes.update_forward_refs()
