# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import Any, List

from pydantic import Field

from .base_model import BaseModel


class ProfileGroupCount(BaseModel):
    profile_group_count: List["ProfileGroupCountProfileGroupCount"] = Field(
        alias="profileGroupCount"
    )


class ProfileGroupCountProfileGroupCount(BaseModel):
    key: str
    count: Any


ProfileGroupCount.update_forward_refs()
ProfileGroupCountProfileGroupCount.update_forward_refs()
