# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import JobStatus


class ProfileJobList(BaseModel):
    jobs: List["ProfileJobListJobs"]


class ProfileJobListJobs(BaseModel):
    job_id: str = Field(alias="jobId")
    is_active: bool = Field(alias="isActive")
    is_cancelled: bool = Field(alias="isCancelled")
    is_complete: bool = Field(alias="isComplete")
    status: JobStatus


ProfileJobList.update_forward_refs()
ProfileJobListJobs.update_forward_refs()
