# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class ProfileSchemaChangeLog(BaseModel):
    profile_history: List["ProfileSchemaChangeLogProfileHistory"] = Field(
        alias="profileHistory"
    )


class ProfileSchemaChangeLogProfileHistory(BaseModel):
    commit_info: "ProfileSchemaChangeLogProfileHistoryCommitInfo" = Field(
        alias="commitInfo"
    )
    project: str


class ProfileSchemaChangeLogProfileHistoryCommitInfo(BaseModel):
    operation: Optional[str]
    timestamp: Any
    version: Any
    user_id: Optional[str] = Field(alias="userId")


ProfileSchemaChangeLog.update_forward_refs()
ProfileSchemaChangeLogProfileHistory.update_forward_refs()
ProfileSchemaChangeLogProfileHistoryCommitInfo.update_forward_refs()
