# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List

from pydantic import Field

from .base_model import BaseModel


class UpdateCustomAttribute(BaseModel):
    update_custom_attribute: "UpdateCustomAttributeUpdateCustomAttribute" = Field(
        alias="updateCustomAttribute"
    )


class UpdateCustomAttributeUpdateCustomAttribute(BaseModel):
    name: str
    custom_attributes: List[
        "UpdateCustomAttributeUpdateCustomAttributeCustomAttributes"
    ] = Field(alias="customAttributes")


class UpdateCustomAttributeUpdateCustomAttributeCustomAttributes(BaseModel):
    name: str
    expression: str


UpdateCustomAttribute.update_forward_refs()
UpdateCustomAttributeUpdateCustomAttribute.update_forward_refs()
UpdateCustomAttributeUpdateCustomAttributeCustomAttributes.update_forward_refs()
