# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from pydantic import Field

from .base_model import BaseModel


class UpdateProfileSchema(BaseModel):
    update_profile_schema: "UpdateProfileSchemaUpdateProfileSchema" = Field(
        alias="updateProfileSchema"
    )


class UpdateProfileSchemaUpdateProfileSchema(BaseModel):
    name: str


UpdateProfileSchema.update_forward_refs()
UpdateProfileSchemaUpdateProfileSchema.update_forward_refs()
