# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from typing import List

from pydantic import Field

from .base_model import BaseModel


class UpdateBucketAttribute(BaseModel):
    update_bucket_attribute: "UpdateBucketAttributeUpdateBucketAttribute" = Field(
        alias="updateBucketAttribute"
    )


class UpdateBucketAttributeUpdateBucketAttribute(BaseModel):
    name: str
    bucket_attributes: List[
        "UpdateBucketAttributeUpdateBucketAttributeBucketAttributes"
    ] = Field(alias="bucketAttributes")


class UpdateBucketAttributeUpdateBucketAttributeBucketAttributes(BaseModel):
    name: str
    buckets: List["UpdateBucketAttributeUpdateBucketAttributeBucketAttributesBuckets"]


class UpdateBucketAttributeUpdateBucketAttributeBucketAttributesBuckets(BaseModel):
    filter: str


UpdateBucketAttribute.update_forward_refs()
UpdateBucketAttributeUpdateBucketAttribute.update_forward_refs()
UpdateBucketAttributeUpdateBucketAttributeBucketAttributes.update_forward_refs()
UpdateBucketAttributeUpdateBucketAttributeBucketAttributesBuckets.update_forward_refs()
