# Generated by ariadne-codegen on 2023-03-10 15:46
# Source: queries/

from pydantic import Field

from .base_model import BaseModel


class UpdateDataSource(BaseModel):
    update_data_source: "UpdateDataSourceUpdateDataSource" = Field(
        alias="updateDataSource"
    )


class UpdateDataSourceUpdateDataSource(BaseModel):
    name: str


UpdateDataSource.update_forward_refs()
UpdateDataSourceUpdateDataSource.update_forward_refs()
