"""
Metadata for cortex-python
"""
__title__ = "cortex-python"
__description__ = "Python module for the CognitiveScale Cortex Cognitive Platform"
__url__ = "https://github.com/CognitiveScale/cortex-python"
__version__ = "6.4.0"
__author__ = "CognitiveScale"
__author_email__ = "support@cognitivescale.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2023 Cognitive Scale, Inc. All Rights Reserved."
