__title__ = 'cortex-python'
__description__ = 'Python module for the CognitiveScale Cortex Cognitive Platform'
__url__ = 'https://github.com/CognitiveScale/cortex-python'
__version__ = '6.0.2'
__author__ = 'CognitiveScale'
__author_email__ = 'me@kennethreitz.org'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2021 Cognitive Scale, Inc. All Rights Reserved.'
