"""
Metadata for cortex-python
"""
__title__ = "cortex-python"
__description__ = "Python module for the Tecnotree Sensa Platform"
__url__ = "https://github.com/CognitiveScale/cortex-python"
__version__ = "6.4.0"
__author__ = "Tecnotree"
__author_email__ = "support@tecnotree.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2024 Tecnotree, Inc. All Rights Reserved."
