format_version: 10
common:
  testreports: &testReports
    coverage: testoutput/coverage/index.html
    test-report: testoutput/coverage/test-report.html
pipelines:
  cortex-python-pr:
    group: pull-requests
    materials:
      cortex-python:
        plugin_configuration:
          id: github.pr
          version: 1
        options:
          url: git@github.com:CognitiveScale/cortex-python.git
          defaultBranch: develop
    environment_variables:
      ALPHA_BUILD: "true"
      SONAR_USER_HOME: "/tmp"
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              artifacts:
                - test:
                    source: coverage
              tabs: *testReports
              elastic_profile_id: gocd-agent-dind-2023
              tasks:
                - script: c12e-ci -l
  cortex-python-develop:
    group: fabric6
    materials:
      cortex-python:
        git: git@github.com:CognitiveScale/cortex-python.git
        branch: develop
    environment_variables:
      ALPHA_BUILD: "true"
      SONAR_USER_HOME: "/tmp"
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              artifacts:
                - test:
                    source: coverage
              tabs: *testReports
              elastic_profile_id: gocd-agent-dind-2023
              tasks:
                - script: |
                    set -eux
                    c12e-common.sh dev
                    sonar-scan.sh scan
  cortex-python-staging:
    group: fabric6
    environment_variables:
      ALPHA_BUILD: "true"
      PYPI_UPLOAD: "https://upload.pypi.org/legacy/"
      REPO_NAME: "cs_internal-local"
      REPO_USER: "cortex5"
      SONAR_USER_HOME: "/tmp"
    secure_variables:
      # LastPass: Shared-devops/Pypi
      REPO_PASSWORD: "AES:VK48nn/zr+mFTMixYa8Psg==:P+AZlJmgChiMcFRyNRmjuwYqBQwkc1hRP8zHck5L5SU="
    materials:
      cortex-python:
        git: git@github.com:CognitiveScale/cortex-python.git
        branch: staging
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              elastic_profile_id: gocd-agent-dind-2023
              tasks:
                - script: |
                    set -eux
                    c12e-common.sh staging
                    sonar-scan.sh scan
                    publish-distribution.sh -i -e
                    
  cortex-python-master:
    group: fabric6
    environment_variables:
      ALPHA_BUILD: "false"
      PYPI_UPLOAD: "https://upload.pypi.org/legacy/"
      REPO_NAME: "cognitivescale_local"
      REPO_USER: "cortex5"
      SONAR_USER_HOME: "/tmp"
    secure_variables:
      # LastPass: Shared-devops/Pypi
      REPO_PASSWORD: "AES:VK48nn/zr+mFTMixYa8Psg==:P+AZlJmgChiMcFRyNRmjuwYqBQwkc1hRP8zHck5L5SU="
    materials:
      cortex-python-master:
        git: git@github.com:CognitiveScale/cortex-python.git
        branch: main
    stages:
      - build:
          clean_workspace: yes
          jobs:
            build:
              tabs: *testReports
              elastic_profile_id: gocd-agent-dind-2023
              artifacts:
                - build:
                    source: cortex-python.docs.tgz
                - test:
                    source: coverage
              tasks:
                - script: |
                    set -eux
                    c12e-common.sh master
                    sonar-scan.sh scan
                    publish-distribution.sh -i -e
      - publish:
          approval:
            type: manual
          clean_workspace: true
          jobs:
            publishJob:
              elastic_profile_id: gocd-agent-dind-2023
              tasks:
                - fetch:
                    pipeline: cortex-python-master
                    stage: build
                    job: build
                    source: cortex-python.docs.tgz
                    is_file: yes
                - script: |
                    publish-gh-pages.sh -d cortex-python.docs.tgz -r git@github.com:CognitiveScale/cortex-python.git -b ${GH_PAGES_BRANCH} -k .nojekyll
